#!/usr/bin/env bash

pid_file="/var/run/myscript.pid"

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; exit' SIGTERM
trap 'rm -f "$pid_file"; exit' SIGQUIT

echo $$ > "$pid_file"
echo "To infinity and beyond"

while true; do
    sleep 1
done

