#!/bin/bash

# Backup the original hosts file
cp /etc/hosts ~/hosts.new

# Define the new mappings
echo "127.0.0.2 localhost" >> ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Overwrite /etc/hosts with the updated file
cp -f ~/hosts.new /etc/hosts
